name: Flask App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install mediapipe
        pip install opencv-python-headless
        pip install numpy
        pip install pytest
        
    - name: Run tests
      run: |
        pytest tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Add your deployment commands here"
        # Example: Deploy to Heroku
        # - uses: akhileshns/heroku-deploy@v3.12.12
        # with:
        #   heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #   heroku_app_name: "your-app-name"
        #   heroku_email: "your-email@example.com"
